Run the test suite with GitHub actions. (#190)
Run the test suite using GitHub actions.

Other minor improvements:

* Use `UV_PYTHON_PREFERENCE=only-system` (as recommended in uv docs,
brings a minor speedup).
* Fix a test case (OpenSSL now requires `-CAFile` for verification).
* Add Dockerfile to test running on different distributions.
* Remove `.travis.yml` file (no longer needed).

Note that the Dockerfile can be used to indeed verify that OpenSSL
3.0.10 and oscrypto have a problem:

On Ubuntu 24.04:

```console
$ docker build --build-arg IMAGE=ubuntu:24.04 -t test .
...
$ docker run --rm -it test 
OpenSSL 3.0.13 30 Jan 2024 (Library: OpenSSL 3.0.13 30 Jan 2024)
$ docker run --rm -it test 
...
.venv/lib/python3.12/site-packages/oscrypto/_openssl/_libcrypto_cffi.py:44: LibraryNotFoundError
===================================================================================================================== short test summary info ======================================================================================================================
FAILED tests/test_public_key_external.py::ExternalPublicKeyTests::test_rsa - oscrypto.errors.LibraryNotFoundError: Error detecting the version of libcrypto
FAILED tests/test_public_key_external.py::ExternalPublicKeyTests::test_terrible_hybrid_file_encryption_app - oscrypto.errors.LibraryNotFoundError: Error detecting the version of libcrypto
== 2 failed, 82 passed, 5 skipped, 1 xfailed in 0.80s ==
```

While on Ubuntu 22.04:

```console
# docker build --build-arg IMAGE=ubuntu:22.04 -t test .
...
$ docker run --rm -it test openssl version
OpenSSL 3.0.2 15 Mar 2022 (Library: OpenSSL 3.0.2 15 Mar 2022)
$ docker run --rm -it test 
== 84 passed, 5 skipped, 1 xfailed in 0.80s ==
```